/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AvroSample extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4093830149797708899L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroSample\",\"fields\":[{\"name\":\"name\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"number\",\"type\":{\"type\":\"array\",\"items\":\"int\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AvroSample> ENCODER =
      new BinaryMessageEncoder<AvroSample>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AvroSample> DECODER =
      new BinaryMessageDecoder<AvroSample>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<AvroSample> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<AvroSample> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AvroSample>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this AvroSample to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a AvroSample from a ByteBuffer. */
  public static AvroSample fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.util.List<java.lang.CharSequence> name;
  @Deprecated public java.util.List<java.lang.Integer> number;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AvroSample() {}

  /**
   * All-args constructor.
   * @param name The new value for name
   * @param number The new value for number
   */
  public AvroSample(java.util.List<java.lang.CharSequence> name, java.util.List<java.lang.Integer> number) {
    this.name = name;
    this.number = number;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return number;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.util.List<java.lang.CharSequence>)value$; break;
    case 1: number = (java.util.List<java.lang.Integer>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.util.List<java.lang.CharSequence> getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.util.List<java.lang.CharSequence> value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'number' field.
   * @return The value of the 'number' field.
   */
  public java.util.List<java.lang.Integer> getNumber() {
    return number;
  }

  /**
   * Sets the value of the 'number' field.
   * @param value the value to set.
   */
  public void setNumber(java.util.List<java.lang.Integer> value) {
    this.number = value;
  }

  /**
   * Creates a new AvroSample RecordBuilder.
   * @return A new AvroSample RecordBuilder
   */
  public static AvroSample.Builder newBuilder() {
    return new AvroSample.Builder();
  }

  /**
   * Creates a new AvroSample RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AvroSample RecordBuilder
   */
  public static AvroSample.Builder newBuilder(AvroSample.Builder other) {
    return new AvroSample.Builder(other);
  }

  /**
   * Creates a new AvroSample RecordBuilder by copying an existing AvroSample instance.
   * @param other The existing instance to copy.
   * @return A new AvroSample RecordBuilder
   */
  public static AvroSample.Builder newBuilder(AvroSample other) {
    return new AvroSample.Builder(other);
  }

  /**
   * RecordBuilder for AvroSample instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroSample>
    implements org.apache.avro.data.RecordBuilder<AvroSample> {

    private java.util.List<java.lang.CharSequence> name;
    private java.util.List<java.lang.Integer> number;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(AvroSample.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.number)) {
        this.number = data().deepCopy(fields()[1].schema(), other.number);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing AvroSample instance
     * @param other The existing instance to copy.
     */
    private Builder(AvroSample other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.number)) {
        this.number = data().deepCopy(fields()[1].schema(), other.number);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.util.List<java.lang.CharSequence> getName() {
      return name;
    }

    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public AvroSample.Builder setName(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public AvroSample.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'number' field.
      * @return The value.
      */
    public java.util.List<java.lang.Integer> getNumber() {
      return number;
    }

    /**
      * Sets the value of the 'number' field.
      * @param value The value of 'number'.
      * @return This builder.
      */
    public AvroSample.Builder setNumber(java.util.List<java.lang.Integer> value) {
      validate(fields()[1], value);
      this.number = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'number' field has been set.
      * @return True if the 'number' field has been set, false otherwise.
      */
    public boolean hasNumber() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'number' field.
      * @return This builder.
      */
    public AvroSample.Builder clearNumber() {
      number = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AvroSample build() {
      try {
        AvroSample record = new AvroSample();
        record.name = fieldSetFlags()[0] ? this.name : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[0]);
        record.number = fieldSetFlags()[1] ? this.number : (java.util.List<java.lang.Integer>) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AvroSample>
    WRITER$ = (org.apache.avro.io.DatumWriter<AvroSample>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AvroSample>
    READER$ = (org.apache.avro.io.DatumReader<AvroSample>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
